### ISSUE TITLE
Only some tokens are shown as their values

### ISSUE THREAD

**Issue by giano574** [oowekyala/intellij-javacc#13]
Only some tokens in productions are "replaced" with their value.

![Screenshot_43](https://user-images.githubusercontent.com/17013720/54828858-60e62d80-4cb5-11e9-94d6-45eb6bbe32ea.png)

Tokens are defined as follows
```
TOKEN : {
  <SPADES: "spades" > |
  <CLUBS: "clubs" > |
  <HEARTS: "hearts" > |
  <DIAMONDS: "diamonds" >
}
```
Version: 1.2

**Comment by oowekyala** [comment]
Hi,

To me there's no problem specifically with the CLUBS token. But when you make a change to the folded form (`"clubs"`), or click directly on it, it unfolds back to the real text, ie `<CLUBS>`.  Intellij doesn't fold it back on itself, but you can get it to fold with right-click (context menu) > Folding > Collapse. I suggest you define a shortcut for that, I personally use it a lot. This is especially useful when you edit the java fragments and want them to fold back when you're done.

Does that fix your issue?

**Comment by oowekyala** [comment]
I'm assuming this wasn't a bug and close this ticket.
