### ISSUE TITLE
Code folding cannot be disabled

### ISSUE THREAD

**Issue by Ansorre** [oowekyala/intellij-javacc#14]
Please can we have a way to TOTALLY disable any code folding at all?
For someone who is learning JavaCC this code folding is really problematic and unfortunately there is no IDE setting that can disable it all the way. 
Thanks anyway.

**Comment by oowekyala** [comment]
Hi, thanks for your insight. It's true there's no way to disable the folding for now... I'll work on it for the next release

Cheers

**Comment by oowekyala** [comment]
The plugin update is pending. When you update, you can disable code folding in `Settings > Editor > General > Code Folding`

I'd be interested in your feedback on what you think the plugin could do better to help learners of JavaCC if you have time. Feel free to open more tickets to discuss that

**Comment by Ansorre** [comment]
Thank you very much!! Yes absolutely I'll give my feedback on what I think the plugin could do better to help learners of JavaCC. In the meantime thank you again.
