### ISSUE TITLE
Nullability annotations not recognized by the plugin

### ISSUE THREAD

**Issue by hiteshsharma** [oowekyala/intellij-javacc#16]
Hi,

The grammar I wrote annotates parameters passed to nodes with Javax Nullability annotations to allow other developers to know the expectation for that param. Though the parser works fine, the IntelliJ plugin shows an error near the annotation and fails to parse rest of the grammar. Can support for Nullability annotations be added in this plugin?

```
void someNode(@Nullable String someString): {}
{
  // grammar
}
```

Thanks

**Comment by oowekyala** [comment]
Thanks for the report, I'll try to work on that this week

**Comment by hiteshsharma** [comment]
Thanks. I would be happy to help. Let me know if I can help.

**Comment by oowekyala** [comment]
I appreciate the thought! But the project is a real hassle to setup inside an IDE for now as it uses a non-standard module organization... I think, it's not worth your time setting it up until this is refactored to be more straightforward

**Comment by oowekyala** [comment]
This is supported in version 1.7, soon to be released
