### ISSUE TITLE
JccDescriptionProvider overrides description of other plugins' types

### ISSUE THREAD

**Issue by jhonnen** [oowekyala/intellij-javacc#22]
``JccDescriptionProvider`` should check the ``PsiElement``'s type, similar to [other implementations](https://upsource.jetbrains.com/idea-ce/file/idea-ce-de81e21aac2d3fad965623adcf42cb78b5e69ef7/platform/lang-api/src/com/intellij/pom/PomDescriptionProvider.java?nav=943:965:focused&line=27&preview=false). Currently it can override the description for `PsiElement`s from different plugins.

**Comment by oowekyala** [comment]
Thanks for the report, I'll fix this this week
