### ISSUE TITLE
Incompatible with latest IntelliJ version

### ISSUE THREAD

**Issue by jrnorth** [oowekyala/intellij-javacc#30]
I have version 1.11 of the plugin installed, and IntelliJ says `Incompatible: requires IDE build 231.* or earlier`.

**Comment by ngx472** [comment]
+1, I have ultimate, build IU-232...

**Comment by rybak** [comment]
Could you please consider leaving the field `untilBuild` (the upper version limit) undefined? That way, you won't need to bump it with every release of IntelliJ IDEA. Here's an example of how I did it in the Gradle build of my plugin: https://github.com/rybak/intellij-copy-commit-reference/commit/64a0eb545ccb6737d32c2c5f6e22cf211bd88b6d

**Comment by oowekyala** [comment]
Thanks for reporting. Will release an update tomorrow.
